services:
  - type: web
    name: employees-api
    env: node
    plan: free
    buildCommand: npm ci
    startCommand: node server.js
    envVars:
      - key: DB_FILE
        value: ./employees.db   # lives on ephemeral FS
